name: pixel_fit
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  cupertino_icons: ^0.1.3
  shared_preferences: ">=0.5.10 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
